tasks:
  - name: Setup Kafka Environment
    init: |
      gp open README.md
      export PUBLIC_IP=127.0.0.1
      echo "Downloading libraries..."
      pip install -r requirements.txt
      cd frontend
      npm install
      cd ..
    command: |
      echo "Starting images..."
      docker-compose up -d

      echo "Waiting for PostgreSQL to initialize..."
      sleep 10

      echo "Starting fast api..."
      uvicorn backend.main:app --reload --port 8000 --host 0.0.0.0 &

      echo "VITE_API_BASE_URL=$(gp url 8000)" > frontend/.env.development

      echo "Starting kafka dashboard..."
      cd frontend
      sleep 10 && npm run dev &   # background React
  
env:
  KAFKAJS_NO_PARTITIONER_WARNING: "1"
  REACT_APP_BACKEND_URL: https://8000-<workspace-id>.ws-us121.gitpod.io #TODO: Validate this and Update apiUrl variable

ports:
  # Kafka Brokers, Zookeeper 
  - port: 2188
    onOpen: ignore
    visibility: private
  - port: 9092
    onOpen: ignore
    visibility: private
  - port: 9093
    onOpen: ignore
    visibility: private
  - port: 9094
    onOpen: ignore
    visibility: private
  - port: 2181
    onOpen: ignore
    visibility: private
  - port: 9992
    onOpen: ignore
    visibility: private
  - port: 9993
    onOpen: ignore
    visibility: private
  - port: 9994
    onOpen: ignore
    visibility: private
  # Kafka Schema Registry 
  - port: 8081
    onOpen: ignore
    visibility: private
  # Fast Api
  - port: 8000
    visibility: public
    onOpen: ignore
  # Kafka Dashboard
  - port: 3000
    visibility: public
    onOpen: open-preview
  # Postgres Database
  - port: 5432
    onOpen: ignore
    visibility: private




vscode:
  extensions:
    - ms-azuretools.vscode-docker    