export const CONFIG_DESCRIPTIONS: Record<string, string> = {
  "log.cleaner.min.compaction.lag.ms": "Minimum time a message remains uncompacted before eligible for compaction.",
  "offsets.topic.num.partitions": "Number of partitions for the internal offsets topic.",
  "log.flush.interval.messages": "Number of messages before triggering a log flush.",
  "controller.socket.timeout.ms": "Timeout for controller socket connections in milliseconds.",
  "principal.builder.class": "Class used to build principal objects for authentication.",
  "log.flush.interval.ms": "Time interval between log flushes in milliseconds.",
  "min.insync.replicas": "Minimum number of replicas that must acknowledge a write for success.",
  "num.recovery.threads.per.data.dir": "Number of threads per data directory for log recovery.",
  "ssl.keystore.type": "Type of keystore used for SSL (e.g., JKS).",
  "zookeeper.ssl.protocol": "SSL protocol version used for Zookeeper connections.",
  "sasl.mechanism.inter.broker.protocol": "SASL mechanism used for inter-broker communication.",
  "fetch.purgatory.purge.interval.requests": "Interval to purge fetch request purgatory.",
  "ssl.endpoint.identification.algorithm": "Algorithm for endpoint verification (e.g., HTTPS).",
  "zookeeper.ssl.keystore.location": "File path for Zookeeper SSL keystore.",
  "replica.socket.timeout.ms": "Socket timeout for replica fetch requests in milliseconds.",
  "message.max.bytes": "Maximum size of a single message allowed.",
  "connections.max.reauth.ms": "Maximum time allowed for re-authentication on a connection.",
  "log.flush.offset.checkpoint.interval.ms": "Interval for writing log flush offset checkpoints.",
  "zookeeper.clientCnxnSocket": "Class used for Zookeeper client connection socket.",
  "zookeeper.ssl.client.enable": "Enable SSL for Zookeeper client connections.",
  "quota.window.num": "Number of windows used for quota calculations.",
  "zookeeper.connect": "Zookeeper connection string (host:port).",
  "authorizer.class.name": "Class implementing Kafka authorizer for ACLs.",
  "password.encoder.secret": "Secret key used by password encoder.",
  "num.replica.fetchers": "Number of threads fetching from leader replicas.",
  "alter.log.dirs.replication.quota.window.size.seconds": "Time window in seconds for replication quota enforcement on log dir changes.",
  "log.roll.jitter.hours": "Random jitter added to log roll interval in hours.",
  "password.encoder.old.secret": "Previous secret used by password encoder for migration.",
  "log.cleaner.delete.retention.ms": "Time to retain delete markers before purging in log compaction.",
  "queued.max.requests": "Maximum number of requests queued per broker connection.",
  "log.cleaner.threads": "Number of background threads for log cleaning.",
  "sasl.kerberos.service.name": "Kerberos service name for SASL authentication.",
  "socket.request.max.bytes": "Maximum size of request that can be received by socket.",
  "log.message.timestamp.type": "Timestamp type for log messages (CreateTime or LogAppendTime).",
  "zookeeper.ssl.keystore.type": "Type of keystore used for Zookeeper SSL.",
  "connections.max.idle.ms": "Maximum idle time before closing a connection.",
  "zookeeper.set.acl": "Enable setting ACLs on Zookeeper znodes.",
  "delegation.token.expiry.time.ms": "Expiration time for delegation tokens in milliseconds.",
  "max.connections": "Maximum number of connections allowed per broker.",
  "transaction.state.log.num.partitions": "Number of partitions in transaction state topic.",
  "listener.security.protocol.map": "Mapping of listener names to security protocols.",
  "log.retention.hours": "Number of hours to retain log segments before deletion.",
  "client.quota.callback.class": "Class to dynamically adjust client quotas.",
  "ssl.provider": "SSL provider implementation to use (default JVM).",
  "delete.records.purgatory.purge.interval.requests": "Interval to purge delete request purgatory.",
  "log.roll.ms": "Time interval in milliseconds to roll new log segments.",
  "ssl.cipher.suites": "Enabled SSL cipher suites.",
  "zookeeper.ssl.keystore.password": "Password for Zookeeper SSL keystore.",
  "security.inter.broker.protocol": "Security protocol used for inter-broker communication.",
  "replica.high.watermark.checkpoint.interval.ms": "Interval for saving replica high-watermark to disk.",
  "replication.quota.window.size.seconds": "Time window in seconds for replication quota enforcement.",
  "sasl.kerberos.ticket.renew.window.factor": "Fraction of ticket lifetime before renewal is attempted.",
  "zookeeper.connection.timeout.ms": "Timeout for Zookeeper connections.",
  "metrics.recording.level": "Recording level for metrics (INFO or DEBUG).",
  "password.encoder.cipher.algorithm": "Cipher algorithm used by password encoder.",
  "ssl.principal.mapping.rules": "Rules to map SSL principal to Kafka principal.",
  "replica.selector.class": "Class to select which replica to fetch from.",
  "max.connections.per.ip": "Maximum connections allowed per client IP.",
  "background.threads": "Number of background threads for various broker tasks.",
  "quota.consumer.default": "Default quota for consumer throughput.",
  "request.timeout.ms": "Default timeout for requests in milliseconds.",
  "log.message.format.version": "Message format version used in logs.",
  "message.timestamp.type": "Timestamp type in messages (deprecated: broker uses log.message.timestamp.type).",
  "sasl.login.class": "Class to handle SASL login.",
  "log.dir": "Directory for log files.",
  "log.segment.bytes": "Maximum size of a single log segment in bytes.",
  "replica.fetch.response.max.bytes": "Maximum bytes a replica fetch response can contain.",
  "group.max.session.timeout.ms": "Maximum allowed session timeout for consumer groups.",
  "port": "Port the broker listens on.",
  "log.segment.delete.delay.ms": "Delay before deleting a log segment.",
  "log.retention.minutes": "Number of minutes to retain log segments (deprecated in favor of hours/ms).",
  "log.dirs": "Directories where Kafka stores data logs.",
  "controlled.shutdown.enable": "Enable controlled shutdown for brokers.",
  "log.message.timestamp.difference.max.ms": "Maximum difference allowed between message timestamp and broker receive time.",
  "password.encoder.key.length": "Key length for password encoder.",
  "sasl.login.refresh.min.period.seconds": "Minimum period between SASL login refreshes.",
  "transaction.abort.timed.out.transaction.cleanup.interval.ms": "Interval to clean up aborted transactions.",
  "sasl.kerberos.kinit.cmd": "Path to kinit executable for Kerberos.",
  "log.cleaner.io.max.bytes.per.second": "Max bytes per second for log cleaner I/O.",
  "auto.leader.rebalance.enable": "Enable automatic leader rebalance.",
  "leader.imbalance.check.interval.seconds": "Interval for checking leader imbalance.",
  "log.cleaner.min.cleanable.ratio": "Minimum ratio of log eligible for compaction before cleaning.",
  "replica.lag.time.max.ms": "Max allowed time a replica can be behind leader.",
  "num.network.threads": "Number of threads handling network requests.",
  "sasl.client.callback.handler.class": "Class handling SASL client callbacks.",
  "metrics.num.samples": "Number of samples maintained for metrics calculation.",
  "socket.send.buffer.bytes": "Size of socket send buffer in bytes.",
  "password.encoder.keyfactory.algorithm": "Algorithm used by password encoder's key factory.",
  "socket.receive.buffer.bytes": "Size of socket receive buffer in bytes.",
  "replica.fetch.min.bytes": "Minimum bytes a replica fetch request waits for before responding.",
  "broker.rack": "Rack or zone where broker is located for replication awareness.",
  "zookeeper.ssl.truststore.password": "Password for Zookeeper SSL truststore.",
  "unclean.leader.election.enable": "Allow non-ISR replicas to become leader on failure.",
  "offsets.retention.check.interval.ms": "Interval to check offsets retention in internal topic.",
  "producer.purgatory.purge.interval.requests": "Interval to purge producer request purgatory.",
  "metrics.sample.window.ms": "Time window for metrics sampling.",
  "log.retention.check.interval.ms": "Interval to check for log retention enforcement.",
  "sasl.login.refresh.window.jitter": "Jitter applied to SASL login refresh window.",
  "leader.imbalance.per.broker.percentage": "Allowed leader imbalance percentage per broker.",
  "advertised.host.name": "Hostname advertised to clients (deprecated in favor of advertised.listeners).",
  "metric.reporters": "Classes to report broker metrics.",
  "quota.producer.default": "Default quota for producer throughput.",
  "auto.create.topics.enable": "Enable automatic creation of topics on access.",
  "ssl.engine.factory.class": "SSL engine factory class.",
  "replica.socket.receive.buffer.bytes": "Size of replica fetch socket receive buffer.",
  "zookeeper.ssl.truststore.location": "File path for Zookeeper SSL truststore.",
  "replica.fetch.wait.max.ms": "Max time a replica fetch request waits if insufficient data.",
  "password.encoder.iterations": "Number of iterations used in password encoding.",
  "default.replication.factor": "Default replication factor for new topics.",
  "ssl.truststore.password": "Password for SSL truststore.",
  "sasl.kerberos.principal.to.local.rules": "Rules mapping Kerberos principals to local user names.",
  "log.preallocate": "Preallocate file sizes for logs.",
  "transactional.id.expiration.ms": "Time before a transactional ID expires.",
  "control.plane.listener.name": "Listener name used for control plane operations.",
  "transaction.state.log.replication.factor": "Replication factor for transaction state log.",
  "num.io.threads": "Number of I/O threads handling disk reads/writes.",
  "sasl.login.refresh.buffer.seconds": "Buffer time for SASL login refresh.",
  "offsets.commit.required.acks": "Number of acknowledgements required for offset commits.",
  "connection.failed.authentication.delay.ms": "Delay after failed authentication before retrying.",
  "delete.topic.enable": "Enable deletion of topics.",
  "quota.window.size.seconds": "Time window in seconds used for client quota calculations.",
  "ssl.truststore.type": "Truststore type for SSL connections.",
  "offsets.commit.timeout.ms": "Timeout for committing offsets.",
  "zookeeper.ssl.ocsp.enable": "Enable OCSP validation for Zookeeper SSL.",
  "log.cleaner.max.compaction.lag.ms": "Maximum time a message can remain uncompacted.",
  "zookeeper.ssl.enabled.protocols": "Enabled SSL protocols for Zookeeper.",
  "log.retention.ms": "Time in milliseconds to retain log segments.",
  "alter.log.dirs.replication.quota.window.num": "Number of windows for log dir replication quota enforcement.",
  "log.cleaner.enable": "Enable background log cleaner threads.",
  "offsets.load.buffer.size": "Buffer size for loading offsets.",
  "ssl.client.auth": "Client authentication mode (none, required, requested).",
  "controlled.shutdown.max.retries": "Maximum retries during controlled shutdown.",
  "offsets.topic.replication.factor": "Replication factor for offsets topic.",
  "zookeeper.ssl.truststore.type": "Type of truststore for Zookeeper SSL.",
  "transaction.state.log.min.isr": "Minimum in-sync replicas for transaction state log.",
  "ssl.secure.random.implementation": "SecureRandom implementation for SSL operations.",
  "sasl.kerberos.ticket.renew.jitter": "Jitter applied to Kerberos ticket renewal time.",
  "ssl.trustmanager.algorithm": "Algorithm used by SSL TrustManager (default PKIX).",
  "zookeeper.session.timeout.ms": "Zookeeper session timeout in milliseconds.",
  "log.retention.bytes": "Maximum size in bytes to retain logs (-1 for unlimited).",
  "sasl.jaas.config": "JAAS configuration for SASL authentication.",
  "sasl.kerberos.min.time.before.relogin": "Minimum time before relogin for Kerberos SASL.",
  "offsets.retention.minutes": "Time in minutes to retain offsets in internal topic.",
  "replica.fetch.backoff.ms": "Backoff time between replica fetch retries.",
  "inter.broker.protocol.version": "Protocol version used between brokers.",
  "kafka.metrics.reporters": "Classes reporting Kafka metrics.",
  "num.partitions": "Default number of partitions for new topics.",
  "broker.id.generation.enable": "Enable automatic broker ID generation.",
  "listeners": "URIs for broker listeners.",
  "ssl.enabled.protocols": "Enabled SSL protocols for broker.",
  "inter.broker.listener.name": "Listener used for inter-broker communication.",
  "alter.config.policy.class.name": "Class implementing policy for altering configs.",
  "delegation.token.expiry.check.interval.ms": "Interval to check expiration of delegation tokens.",
  "log.flush.scheduler.interval.ms": "Interval for scheduled log flushes.",
  "zookeeper.max.in.flight.requests": "Maximum number of in-flight requests to Zookeeper.",
  "log.index.size.max.bytes": "Maximum size of log index file.",
  "ssl.keymanager.algorithm": "Algorithm used by SSL KeyManager (default SunX509).",
  "sasl.login.callback.handler.class": "Callback handler class for SASL login.",
  "replica.fetch.max.bytes": "Maximum bytes a replica fetch request can receive.",
  "zookeeper.ssl.crl.enable": "Enable CRL validation for Zookeeper SSL.",
  "sasl.server.callback.handler.class": "Callback handler class for SASL server.",
  "log.cleaner.dedupe.buffer.size": "Buffer size for log cleaner deduplication.",
  "advertised.port": "Port advertised to clients (deprecated).",
  "log.cleaner.io.buffer.size": "Buffer size for log cleaner I/O.",
  "create.topic.policy.class.name": "Class implementing topic creation policy.",
  "controlled.shutdown.retry.backoff.ms": "Backoff between controlled shutdown retries.",
  "security.providers": "Security providers used by the broker.",
  "log.roll.hours": "Time in hours before rolling a new log segment.",
  "log.cleanup.policy": "Policy for cleaning up logs (delete or compact).",
  "log.flush.start.offset.checkpoint.interval.ms": "Interval to checkpoint start offsets during flush.",
  "host.name": "Hostname for broker (deprecated).",
  "log.roll.jitter.ms": "Random jitter in milliseconds added to log roll interval.",
  "transaction.state.log.segment.bytes": "Segment size for transaction state log.",
  "offsets.topic.segment.bytes": "Segment size for offsets topic.",
  "jmx.hostname": "Hostname for JMX server.",
  "group.initial.rebalance.delay.ms": "Initial delay for group rebalance.",
  "log.index.interval.bytes": "Interval between index entries in log.",
  "log.cleaner.backoff.ms": "Backoff between log cleaner runs.",
  "ssl.truststore.location": "Path to SSL truststore file.",
  "offset.metadata.max.bytes": "Maximum bytes for offset metadata.",
  "ssl.keystore.password": "Password for SSL keystore.",
  "zookeeper.sync.time.ms": "Max time Zookeeper can be out of sync.",
  "fetch.max.bytes": "Maximum bytes a fetch request can return.",
  "compression.type": "Default compression type for messages (none, gzip, snappy, lz4, producer).",
  "max.connections.per.ip.overrides": "Overrides for max connections per IP.",
  "sasl.login.refresh.window.factor": "Fraction of refresh window used for SASL login refresh.",
  "kafka.metrics.polling.interval.secs": "Interval in seconds to poll Kafka metrics.",
  "max.incremental.fetch.session.cache.slots": "Maximum slots for incremental fetch session cache.",
  "delegation.token.master.key": "Master key for delegation token encryption.",
  "ssl.key.password": "Password for private key in SSL keystore.",
  "reserved.broker.max.id": "Maximum reserved broker ID.",
  "transaction.remove.expired.transaction.cleanup.interval.ms": "Interval to remove expired transactions.",
  "log.message.downconversion.enable": "Enable down-conversion of old message formats.",
  "ssl.protocol": "SSL protocol to use for broker connections.",
  "transaction.state.log.load.buffer.size": "Buffer size for loading transaction state log.",
  "ssl.keystore.location": "Path to SSL keystore file.",
  "sasl.enabled.mechanisms": "SASL mechanisms enabled on broker.",
  "num.replica.alter.log.dirs.threads": "Threads used for altering log dirs for replicas.",
  "zookeeper.ssl.cipher.suites": "SSL cipher suites for Zookeeper.",
  "group.min.session.timeout.ms": "Minimum allowed session timeout for consumer groups.",
  "log.cleaner.io.buffer.load.factor": "Load factor for log cleaner I/O buffer.",
  "transaction.max.timeout.ms": "Maximum allowed transaction timeout.",
  "group.max.size": "Maximum number of members in a consumer group.",
  "delegation.token.max.lifetime.ms": "Maximum lifetime of delegation tokens.",
  "broker.id": "Unique broker identifier.",
  "offsets.topic.compression.codec": "Compression codec used for offsets topic.",
  "zookeeper.ssl.endpoint.identification.algorithm": "Algorithm to verify Zookeeper endpoint identity.",
  "replication.quota.window.num": "Number of windows for replication quota calculation.",
  "advertised.listeners": "Listeners advertised to clients.",
  "jmx.port": "Port for JMX server.",
  "queued.max.request.bytes": "Maximum size of queued requests in bytes."
};
